name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  ci:
    name: Test & Lint
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.17.1]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install
      run: yarn install --immutable
    - name: Test
      run: yarn run test
      env:
        HEADLESS: true
    - name: Lint
      run: yarn run lint
  check-e2e-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.17.1
        uses: actions/setup-node@v2
        with:
          node-version: 18.17.1

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          start: yarn start
          browser: chrome
          headed: true
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
